

GET https://postman-echo.com/get
x-api-key: test

###

POST https://postman-echo.com/post
Content-Type: application/json

{
	"name": "louis77"
}

###

POST https://postman-echo.com/post
Content-Length: ()

< /Users/louis/payload.json

###

GET https://wikipedia.org
Content-Type: application/json
Connection: 

teste 
yxc

###

HEAD https://wikipedia.org/
Content-Type: application/json
User-Agent: nova/1.3

bdy  

###

GET http://worldtimeapi.org/api/timezone/Europe/Zurich

###

GET https://en.wikipedia.org/w/api.php?action=query&prop=imageinfo&format=xml&iiprop=url&titles=File%3ABruce_Willis_by_Gage_Skidmore.jpg
