
GET https://postman-echo.com/get
x-api-key: test

###

POST https://postman-echo.com/post
Content-Type: application/json

{
	"name": "louis77"
}

###

GET https://wikipedia.org

###

HEAD https://wikipedia.org/
Content-Type: application/json

body

###

GET http://worldtimeapi.org/api/timezone/Europe/Zurich

