GET http://localhost:8080

POST http://localhost:8080

GET hxttps://wikipedia.org

HEAD https://wikipedia.org

GET http://worldtimeapi.org/api/timezone/Europe/Zurich

# doesn't work
GET https://raw.githubusercontent.com/louis77/nova-http-client/main/extension.png